language: ruby
rvm:
  - 2.5.1
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --skip-save-results -w https://www.gitprime.com/engineering-impact/ -w https://www.reddit.com/newsletter --allow-ssl
